export const titles = [
  'Air Commodore',
  'Archduke',
  'Brigadier',
  'Brigadier',
  'Captain',
  'Colonel',
  'Commander',
  'Commodore',
  'Dame',
  'District Judge',
  'Dr',
  'Earl',
  'Emperor',
  'General',
  'Group Captain',
  'H. H. Sheik',
  'H.E.',
  'HRH',
  'Her Hon. Judge',
  'His Hon. Judge',
  'Lady',
  'Lord',
  'Lt.',
  'Lt. Col',
  'Madam',
  'Major',
  'Marquess',
  'Miss',
  'Mr',
  'Mr &amp; Mr',
  'Mr &amp; Mrs',
  'Mrs',
  'Mrs &amp; Mrs',
  'Ms',
  'Mx',
  'Priest',
  'Prof',
  'Rabbi',
  'Rev',
  'Reverend Mother',
  'Sergeant',
  'Sir',
  'Sister',
  'Squadron Leader',
  'The Hon. Mr Justice',
  'The Hon. Mrs Justice',
  'The Hon. Ms Justice',
  'The Lady',
  'The Lord',
  'The Marchioness',
  'The Marquess',
  'The Most Revd',
  'The Revd',
  'The Revd Canon',
  'The Rt. Hon',
  'The Rt. Rev',
  'The Venerable',
  'The Very Revd',
  'Tsar',
  'Viscount',
  'Viscountess',
  'Wing Commander',
]
